version: "3.7"

services:
  bookingdotcom:
    restart: always
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: bookingdotcom_dev
    container_name: bookingdotcom_dev
    volumes:
      - .:/bookingdotcom:z
    ports:
      - 8080:8080
    depends_on:
      - bookingdotcom-mongo
      - bookingdotco-mongo-express

  bookingdotcom-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bookingdotcom

  bookingdotco-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@bookingdotcom-mongo:27017/
